<?php

/****************************
*** DO NOT EDIT THIS FILE ***
****************************/

/** [STATIC] **/

/** [PATH] **/
/* path to class folder */
$GLOBALS['config']['core']['path']['class'] = 'class' . DIRECTORY_SEPARATOR;
/* path to config folder */
$GLOBALS['config']['core']['path']['config'] = 'config' . DIRECTORY_SEPARATOR;
/* path to lang folder */
$GLOBALS['config']['core']['path']['lang'] = 'lang' . DIRECTORY_SEPARATOR;
/* path to locale folder */
$GLOBALS['config']['core']['path']['locale'] = 'locale' . DIRECTORY_SEPARATOR;
/* path to mod folder */
$GLOBALS['config']['core']['path']['mod'] = 'mod' . DIRECTORY_SEPARATOR;
/* path to template folder */
$GLOBALS['config']['core']['path']['template'] = 'template' . DIRECTORY_SEPARATOR;
/** [/PATH] **/

/** [CONFIG] **/
/* config file name */
$GLOBALS['config']['core']['config']['filename'] = 'config.php';
/** [/CONFIG] **/

/** [LANG] **/
/* lang file name */
$GLOBALS['config']['core']['lang']['filename'] = 'lang.php';
/** [/LANG] **/

/** [LOCALE] **/
/* locale file name */
$GLOBALS['config']['core']['locale']['filename'] = 'locale.php';
/** [/LOCALE] **/

/** [LOGIN] **/
/** [GUEST] **/
/* guest nickname */
$GLOBALS['config']['core']['login']['guest']['nickname'] = 'guest';
/* guest password */
$GLOBALS['config']['core']['login']['guest']['password'] = 'guest';
/* guest id */
$GLOBALS['config']['core']['login']['guest']['id'] = 1;
/** [/GUEST] **/
/** [/LOGIN] **/

/** [MOD] **/
/* filename of the index of installed mod */
$GLOBALS['config']['core']['mod']['index_file'] = 'installed';
/* filename of installation script */
$GLOBALS['config']['core']['mod']['install_file'] = 'install.php';
/** [/MOD] **/

/** [/STATIC] **/

/** [DYNAMIC] **/

/** [ROUTE] **/
/* default error route id */
$GLOBALS['config']['core']['route']['error']['id'] = 1;
/** [/ROUTE] **/

/** [LANG] **/
/* lang of the server */
$GLOBALS['config']['core']['lang']['server'] = 'en';
/** [/LANG] **/

/** [LOCALE] **/
/* default locale */
$GLOBALS['config']['core']['locale']['default'] = 'en';
/** [/LOCALE] **/

/** [ROUTER] **/
/* default mode of the router */
$GLOBALS['config']['core']['router']['default'] = 3;
/** [/ROUTER] **/

/** [/DYNAMIC] **/


?>
